/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;

 import javax.swing.JOptionPane.*;

/**
 *
 * @author Lenovo
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    int score,flag=0;
    public Main_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        enggRadio = new javax.swing.JRadioButton();
        medicalRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        scoreField = new javax.swing.JTextField();
        showButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


         jLabel1.setText("Enter Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        buttonGroup.add(enggRadio);
        enggRadio.setText("Engineering");
        enggRadio.addActionListener(new java.awt.event.ActionListener() {
            JTextField testField=new JTextField(10);
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enggRadioActionPerformed(evt);
                String textFieldValue=testField.getText();
            }
        });

        buttonGroup.add(medicalRadio);
        medicalRadio.setText("Medical");
        medicalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRadioActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Percentage");

        scoreField.addActionListener(new java.awt.event.ActionListener() {
            JTextField scorefield=new JTextField(10);

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String scorefieldvalue=scorefield.getText();
                int score=Integer.parseInt(scorefieldvalue);
                scoreFieldActionPerformed(evt);
            }
        });

        showButton.setText("Show Colleges");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);

            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("College Recommendation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(medicalRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enggRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 141, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(enggRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(medicalRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(showButton)
                                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void scoreFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String command= evt.getActionCommand();
        if(command.equals("Show Colleges")){
            mymethod();
        }
    }
    public void mymethod(){
        if(score>=90 && score<=100){
            System.out.format("Veermata Jijabai Technological Institute(VJTI), Matunga, Mumbai \n Manjara Charitable Trust's Rajiv Gandhi Institute of Technology, Mumbai" +
                    "\n Vidyalankar Institute of Technology,Wadala, Mumbai" +
                    "\n Mahavir Education Trust's Shah & Anchor Kutchhi Engineering , Mumbai\n" +
                    "Thakur College of Engineering and Technology, Kandivali, Mumbai\n" +
                    "Thadomal Shahani Engineering College, Bandra, Mumbai\n" +
                    "Conceicao Rodrigues College of Engineering, Bandra,Mumbai\n" +
                    "Vivekanand Education Society's Institute of Technology, Chembur, Mumbai\n" +
                    "N.Y.S.S.'s Datta Meghe College of Engineering, Airoli, Navi Mumbai\n" +
                    "Bharati Vidyapeeth College of Engineering, Navi Mumbai\n" +
                    "Terna Engineering College, Nerul, Navi Mumbai");

        }
        else if(score>=80 && score<90){
            System.out.format("Usha Mittal Institute of Technology SNDT Women's University, Mumbai\n" +
                    "M.G.M.'s College of Engineering and Technology, Kamothe, Navi Mumbai\n" +
                    "Anjuman-I-Islam's M.H. Saboo Siddik College of Engineering, Mumbai\n" +
                    "Vasantdada Patil Pratishthan's College Of Engineering , Mumbai\n" +
                    "Smt. Indira Gandhi College of Engineering, Navi Mumbai\n" +
                    "Shivajirao S. Jondhale College of Engineering, Dombivali,Mumbai\n" +
                    "Lokmanya Tilak College of Engineering, Kopar Khairane, Navi Mumbai\n" +
                    "Shree L.R. Tiwari College of Engineering, Mira Road, Mumbai\n" +
                    "TSSMS's Pd. Vasantdada Patil Institute of Technology, Bavdhan, Pune\n" +
                    "JSPM's Imperial College of Engineering and Research, Wagholi, Pune\n" +
                    "Indira College of Engineering & Management, Pune\n" +
                    "Sinhgad Academy of Engineering, Kondhwa (BK) Kondhwa-Saswad Road, Pune\n" +
                    "Marathwada Mitra Mandal's Institute of Technology, Lohgaon, Pune\n" +
                    "Pune District Education Association's College of Engineering, Pune\n" +
                    "Nagesh Karajagi Orchid College of Engineering & Technology, Solapur");
        }
        else if(score>=70 && score<80){
            System.out.format("Genba Sopanrao Moze Trust Parvatibai Genba Moze College of Engineering, Pune\n" +
                    "Genba Sopanrao Moze College of Engineering, Baner-Balewadi, Pune\n" +
                    "Siddhant College of Engineering, A/p Sudumbare, Tal.Maval, Dist-Pune\n" +
                    "Alard Charitable Trust's Alard College of Engineering and Management, Pune\n" +
                    "Nutan College of Engineering and Research, Talegaon Dabhade Tal. Maval, Pune\n" +
                    "N. B. Navale Sinhgad College of Engineering, Kegaon, solapur\n" +
                    "Sahyadri Valley College of Engineering & Technology, Rajuri, Pune.\n" +
                    "Shree Ramchandra College of Engineering, Lonikand,Pune\n" +
                    "P.K. Technical Campus, Pune.\n" +
                    "SKN Sinhgad Institute of Technology & Science, Kusgaon(BK),Pune.\n" +
                    "Keystone School of Engineering, Pune");
        }
        else if(score>=60 && score<70){
            System.out.println("Kai Amdar Bramhadevdada Mane Shikshan & Samajik Prathistan's Bramhadevdada Mane Institute of Technology, Solapur\n" +
                    "Shanti Education Society, A.G. Patil Institute of Technology, Soregaon, Solapur(North)\n" +
                    "Samarth Group of Institutions, Bangarwadi, Post Belhe Tal. Junnar Dist. Pune\n" +
                    "Suman Ramesh Tulsiani Technical Campus: Faculty of Engineering, Kamshet,Pune.");
        }
    }

    private void enggRadioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(evt.getSource()==enggRadio){
           flag=1;
        }
    }

    private void medicalRadioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //double score=JOptionPane.showInputDialogue("Enter you score here");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton enggRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton medicalRadio;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField scoreField;
    private javax.swing.JButton showButton;
    // End of variables declaration
}

